### ISSUE TITLE
NiBabies integration

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#206]
@mgxd I'm getting the following problem:

```
Node: nibabies_wf.single_subject_01_wf.fmap_preproc_wf.wf_auto_00000.unwarp
Working directory: /work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/unwarp

Node inputs:

in_coeff = <undefined>
in_target = <undefined>
pe_dir = <undefined>
ro_time = [1.0]

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/interfaces/bspline.py", line 263, in _run_interface
    xfm.apply(nb.load(fname), ro_time=ro, pe_dir=pe).to_filename(out_name)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/transform.py", line 132, in apply
    prefilter=prefilter,
  File "/usr/local/miniconda/lib/python3.7/site-packages/scipy/ndimage/interpolation.py", line 326, in map_coordinates
    shape=output_shape)
  File "/usr/local/miniconda/lib/python3.7/site-packages/scipy/ndimage/_ni_support.py", line 82, in _get_output
    raise RuntimeError("output shape not correct")
RuntimeError: output shape not correct
```

Recently, I've started to see more often that crashfiles don't have info about inputs. Anyways, I could retrieve them from the report file:

```
* in_coeff : ['/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/fix_coeff/sub-01_dir-AP_epi_idx-000_merged_base_fieldcoef_fixed.nii.gz']
* in_target : ['/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-000.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-001.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-002.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-003.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-004.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-005.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-006.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-007.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-008.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-000.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-001.n
ii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-002.nii.gz', '/wo
rk/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-003.nii.gz', '/work/nibabies_
wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-004.nii.gz', '/work/nibabies_wf/single_su
bject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-005.nii.gz', '/work/nibabies_wf/single_subject_01_wf/
fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-006.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc
_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-007.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_
00000/flatten/sub-01_dir-PA_epi_idx-008.nii.gz']
* pe_dir : ['j-', 'j-', 'j-', 'j-', 'j-', 'j-', 'j-', 'j-', 'j-', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j']
* ro_time : [0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.
0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409]
```

If I run the interface manually with those values, it works:

```
ApplyCoeffsField(in_coeff=in_coeff, in_target=in_target, ro_time=ro_time, pe_dir=pe_dir).run()
```
and I've checked the outputs are written and available through the output object.

Why is it not working within the NiBabies workflow?

**Comment by oesteban** [comment]
After https://github.com/nipreps/sdcflows/commit/c0d02450213e97f3b2f728a1752f68740bd29f3f, the crash is still happening, but at least the crashfile looks good:

```
Node: nibabies_wf.single_subject_01_wf.fmap_preproc_wf.wf_auto_00000.unwarp
Working directory: /work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/unwarp

Node inputs:

in_coeff = ['/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/fix_coeff/sub-01_dir-AP_epi_idx-000_merged_base_fieldcoef_fixed.nii.gz']
in_target = ['/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-000.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-001.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-002.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-003.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-004.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-005.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-006.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-007.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-AP_epi_idx-008.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-000.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-001.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-002.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-003.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-004.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-005.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-006.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-007.nii.gz', '/work/nibabies_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/flatten/sub-01_dir-PA_epi_idx-008.nii.gz']
pe_dir = ['j-', 'j-', 'j-', 'j-', 'j-', 'j-', 'j-', 'j-', 'j-', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j']
ro_time = [0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.05
97409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409, 0.0597409]

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/interfaces/bspline.py", line 263, in _run_interface
    xfm.apply(nb.load(fname), ro_time=ro, pe_dir=pe).to_filename(out_name)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/transform.py", line 132, in apply
    prefilter=prefilter,
  File "/usr/local/miniconda/lib/python3.7/site-packages/scipy/ndimage/interpolation.py", line 326, in map_coordinates
    shape=output_shape)
  File "/usr/local/miniconda/lib/python3.7/site-packages/scipy/ndimage/_ni_support.py", line 82, in _get_output
    raise RuntimeError("output shape not correct")
RuntimeError: output shape not correct
```

**Comment by oesteban** [comment]
It does seem like a scipy version problem. I was mistakenly using an old container with 1.1. Upgrading to 1.6 seems to solve this. Thanks for the tip @mgxd
