### ISSUE TITLE
CI: pypi deployment failing

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#24]
@effigies have you ever seen something like:

```
Processing ./dist/sdcflows-0.1.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-v9krq8c7/setup.py", line 26, in <module>
        main()
      File "/tmp/pip-req-build-v9krq8c7/setup.py", line 13, in main
        import versioneer
    ImportError: No module named 'versioneer'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-v9krq8c7/
```

**Comment by effigies** [comment]
sdist requires a `MANIFEST.in`. My guess is it's that.

**Comment by oesteban** [comment]
Right, because of that the local versioneer module is not being picked. Very much appreciated.
